server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  # Forward /api calls to auth-service (and other services later)
  location /api/auth/ {
    proxy_pass http://agrosense-auth:4001;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  # SPA fallback — all other routes serve index.html
  location / {
    try_files $uri $uri/ /index.html;
  }
}
