// Entity type is generated by Prisma — import Observation from '@prisma/client'

export interface CreateObservationDto {
  farm_id: string;
  crop_id?: string;
  soil_moisture?: number;
  temperature_c?: number;
  notes?: string;
  observed_at?: string;
}
