// Entity type is generated by Prisma — import Recommendation from '@prisma/client'
// Enum types: Urgency, RecommendationSource, ReviewStatus from '@prisma/client'

export interface CreateRecommendationDto {
  farm_id: string;
  observation_id?: string;
  event_id: string;
  action: string;
  urgency: string;
  message: string;
  source: string;
  context_json?: Record<string, unknown>;
}
