apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploy monitoring stack: kubectl apply -k iac/k8s/monitoring/

resources:
  - namespace.yaml
  - prometheus-configmap.yaml
  - prometheus.yaml
  - grafana.yaml
  - node-exporter.yaml

namespace: monitoring
