[agrosense_vps]
# Replace YOUR_VPS_IP with the output of `terraform output droplet_ip`
agrosense ansible_host=167.99.12.201 ansible_user=root ansible_connection=local

[agrosense_vps:vars]
ansible_python_interpreter=/usr/bin/python3
